services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=logpulsedb
      - POSTGRES_USER=postgres
      # IMPORTANT: Make sure this password matches the one you use below
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # IMPORTANT: Use the same password here. The hostname is 'db'
      - DATABASE_URL=postgresql://postgres:postgres@db/logpulsedb
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
